# Використовуємо той самий базовий образ
FROM python:3.10-slim

# Встановлюємо locust
RUN pip install locust

# Копіюємо ТІЛЬКИ файл сценарію
COPY locustfile.py .

# 1. Встановлюємо змінну $PORT за замовчуванням
ENV PORT 8080

# 2. Відкриваємо цей порт
EXPOSE 8080

# 3. Тепер CMD завжди бачитиме $PORT (або 8080, або те, що дасть Cloud Run)
CMD sh -c 'locust -f locustfile.py --web-port $PORT --web-host 0.0.0.0'
